### PR TITLE
Update pandoc_scratchblocks (with translation fix)

### PR DESCRIPTION
**Pull request by andylolz**

### CODE REVIEW

**Comment by martinpeck** [comment]
Thanks!

Let's see if @CodeClubRik manages to revert this ;)

**Comment by martinpeck** [comment]
@CodeClubRik : A perfectly timed blog post from GitHub https://github.com/blog/2104-working-with-submodules

**Comment by andylolz** [comment]
Haha, nice :)

**Comment by CodeClubRik** [comment]
> Let's see if @CodeClubRik manages to revert this ;)

I'd say it's more than likely! I HATE submodules.

**Comment by andylolz** [comment]
@CodeClubRik: Here’s the most useful bit, I reckon:

>  * Remember that collaborators won't automatically see updates to submodules—if you update a submodule, you may need to remind your colleagues to run `git submodule update` or they will likely see odd behavior.

**Comment by martinpeck** [comment]
For me, the warning signs come when...

1. My clone says I don't have any changes locally (either via `git status` or through my command line prompt)
2. I `git pull` without needing to merge
3. It now appears that I have local changes

That should never happen, and it almost always cos of a submodule.

**Comment by andylolz** [comment]
> That should never happen

If `git pull` fetched recursively, I think this would be true. You can _possibly_ do:

```
git pull --recurse-submodules
```

…and I guess that would elicit the behaviour you’re looking for.

**Pull request merged**
