### PR TITLE
[#36] Move formatting stuff out of README

### PR DESCRIPTION
**Pull request by andylolz**
Refs #36.

### CODE REVIEW

**Comment by arve0** [comment]
Remember to remove links in README.md also.

**Comment by andylolz** [comment]
Remove links to what?

This PR is mega old – the formatting guide has since moved to a new repo.

**Comment by arve0** [comment]
Sorry, did not look at the date. Just saw that `FORMATTING.md` was missing, and the link in readme wasn't updated. See it is [fixed](https://github.com/CodeClub/lesson_format/commit/c615877b76aeab013defdc298cd0713a3d142f89) now

**Comment by andylolz** [comment]
Ohh! Unrelated to this PR, but an excellent spot nonetheless! Thanks!

**Pull request merged**
