### PR TITLE
Remove pandoc_scratchblocks submodule

### PR DESCRIPTION
**Pull request by andylolz**
This reverts #96.

### CODE REVIEW

**Comment by martinpeck** [comment]
Sorry - I've not been paying attention to this.

Why have we removed the submodule? 
What does this fix?
How should Heroku now build these projects?

**Comment by andylolz** [comment]
> Why have we removed the submodule? 

Submodules are tricky to work with. This tool works just as well (if not better) without any. It previously worked without a submodule (see #96).

> What does this fix?

This is part of the fix for CodeClub/#400. The other option was to update the submodule, which I gave as an alternative [in this comment](https://github.com/CodeClub/scratch-curriculum/issues/400#issuecomment-179898235).

More generally, this prevents the possibility of accidentally reverting the submodule.

> How should Heroku now build these projects?

I don’t believe any changes are necessary. If heroku still runs `make clone` then I _think_ this should just work as is.

**Comment by martinpeck** [comment]
Thanks for this @andylolz, but I've reverted @rikcross's merge of this PR for a couple of reasons...

1. Heroku gets really upset if you remove a submodule. I believe you have to reset the repository on Heroku to get around this problem. When we tried to push the merged version (without submodules) Heroku failed on push because it was trying to update submodules that didn't exist. I couldn't find anything definitive that confirmed that nuking things would work (or, what other problems this might cause) so I was reluctant to do this.

2. Better the devil you know. Submodules are a pain at times, but it's a pain we understand.

Anyway, that's the reason why we're living with submodules.

**Comment by andylolz** [comment]
Righto. Well then the submodule version will need updating. I’ll send a PR for that now.

**Pull request merged**
