### PR TITLE
Replace “beta” with “new” various places.

### LINKED ISSUE #128: Remove “beta” / replace with “new”
A volunteer at the London meetup mentioned it’s a bit weird that the printed PDFs say “beta” in the titles. I think I agree – this is definitely more of a volunteer-facing thing. We currently strip the “heads up!” text out of the PDFs, so maybe we should also strip the title prefix.

One simple way to do this (and tidy up a bit on the way) would be to add support for `beta: true` in the frontmatter of project markdown. When this flag is set, the “heads up!” and “beta” messages are automatically added to the html (but hidden from the PDF).

### PR DESCRIPTION
**Pull request by andylolz**
@CodeClubRik I’ll push this to heroku now, so you can see a demo of the output before merging.

Fixes #128.

### CODE REVIEW

**Comment by andylolz** [comment]
Okay – you can see a preview of this here:
http://codeclubrobot.github.io/CodeClubUK-Projects/

**Comment by CodeClubRik** [comment]
That's exactly what I was after!! Thanks @andylolz 
This build also contains a new project, so we can merge this! :)

**Comment by andylolz** [comment]
Great :)

**Comment by andylolz** [comment]
I’ve merged the change here, deployed to heroku and have re-run the builds on UK and World.

**Comment by CodeClubRik** [comment]
Thanks @andylolz :)

**Pull request merged**
